# https://github.com/elastic/beats/blob/master/metricbeat/metricbeat.reference.yml

#-------------------------------- Autodiscovery -------------------------------
# Autodiscover allows you to detect changes in the system and spawn new modules as they happen.
metricbeat.autodiscover:
  providers:
    - type: docker
      # https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover-hints.html
      hints.enabled: true

metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml

metricbeat.modules:
#------------------------------- System Module -------------------------------
- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: ["http://${ELASTICSEARCH_HOST}:9200"]
  username: "elastic"
  password: "${ELASTICSEARCH_PASSWORD}"

- module: system
  metricsets: ["cpu", "load", "memory", "network", "process", "process_summary", "core", "diskio", "socket"]
  processes: ['.*']
  process.include_top_n:
    by_cpu: 5
    by_memory: 5
  period: 10s
  cpu.metrics:  ["percentages"]
  core.metrics: ["percentages"]

- module: system
  period: 1m
  metricsets:
    - filesystem
    - fsstat
  processors:
  - drop_event.when.regexp:
      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'

- module: system
  period: 15m
  metricsets:
    - uptime

#------------------------------- Docker Module -------------------------------
- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s

#================================ Processors ===================================
processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~
- add_locale:
    format: offset
- add_host_metadata:
    netinfo.enabled: true

#========================== Elasticsearch output ===============================
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOST}:9200"]
  protocol: "https"
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}
  ssl:
    certificate_authorities: ["/usr/share/elasticsearch/config/certificates/ca/ca.crt"]
    # verification_mode: "certificate"

#============================== Dashboards =====================================
setup.dashboards:
  enabled: true

#============================== Kibana =========================================
setup.kibana:
  host: "kibana:5601"
  protocol: "https"
  ssl.enabled: true
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}
  ssl:
    certificate_authorities: ["/usr/share/elasticsearch/config/certificates/ca/ca.crt"]
    # verification_mode: "certificate"

    # certificate_authorities: ["/etc/pki/root/ca.pem"]
    # certificate: "/etc/pki/client/cert.pem"
    # key: "/etc/pki/client/cert.key"

#============================== Xpack Monitoring ===============================
xpack.monitoring:
  enabled: true
  elasticsearch: